Repository GDSC-SKHU/98developers-flutter-app, pull requests merged in 2023-03, with the labels that each got.

#26 PR#8 Styling explore screen
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/cubits/google_map_cubit.dart
  lib/cubits/google_map_state.dart
  lib/screens/explore.dart
  pubspec.lock
  pubspec.yaml
Labels: :love_letter: pull request

#29 PR#9 Styling home
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  lib/screens/home.dart
  lib/widgets/light_appbar.dart
  lib/widgets/next_button.dart
Labels: :love_letter: pull request

#30 PR#10 styling profile
  lib/screens/profile.dart
Labels: :love_letter: pull request

#32 PR#11 styling challenge
  lib/screens/challenge.dart
Labels: :love_letter: pull request

#33 PR#12 styling home
  lib/screens/home.dart
Labels: :love_letter: pull request

#40 PR#13 Feat ads
  lib/screens/home.dart
  pubspec.lock
  pubspec.yaml
Labels: :love_letter: pull request

#41 PR#14 Feat/auth
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  assets/images/app_zikiza.png
  assets/images/app_zikiza_dark.png
  assets/images/app_zikiza_light.png
  assets/images/google_light.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/AppDelegate.swift
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  ios/firebase_app_id_file.json
  lib/cubits/google_auth_cubit.dart
  lib/cubits/google_auth_state.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/screens/initial.dart
  lib/screens/launch.dart
  lib/widgets/light_appbar.dart
  lib/widgets/next_button.dart
  pubspec.lock
  pubspec.yaml
Labels: :love_letter: pull request

#42 PR#15 Feat submission
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/screens/home.dart
  lib/screens/submission.dart
Labels: :love_letter: pull request

#46 Feat/infowindow
  assets/images/custom_marker.png
  lib/cubits/google_map_cubit.dart
  lib/cubits/google_map_state.dart
  lib/models/explore_bundle.dart
  lib/screens/explore.dart
  lib/utilities/constants.dart
Labels: :love_letter: pull request

#47 Feat/challenges
  ios/Podfile.lock
  lib/cubits/challenge_enroll_cubit.dart
  lib/cubits/challenge_enroll_state.dart
  lib/cubits/challenge_list_cubit.dart
  lib/cubits/challenge_list_state.dart
  lib/main.dart
  lib/models/getChallenge.dart
  lib/models/getUserData.dart
  lib/models/post_enroll.dart
  lib/models/post_submission.dart
  lib/screens/challenge.dart
  lib/screens/enroll.dart
  lib/screens/home.dart
  lib/screens/submission.dart
  pubspec.lock
  pubspec.yaml
Labels: :sparkles: feature

#48 PR#17 Feat/infowindow
  ios/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
Labels: :love_letter: pull request

#52 PR#20 feat pay
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/cubits/challenge_list_cubit.dart
  lib/models/user_data_service.dart
  lib/screens/challenge.dart
  lib/screens/enroll.dart
  lib/screens/home.dart
  lib/screens/pay.dart
  pubspec.lock
  pubspec.yaml
Labels: :sparkles: feature

#53 PR#21 feat add image link
  ios/Podfile.lock
  lib/screens/enroll.dart
  lib/screens/home.dart
  pubspec.lock
  pubspec.yaml
Labels: :sparkles: feature

#54 PR#22 styling ui
  .vscode/launch.json
  lib/screens/challenge.dart
  lib/screens/enroll.dart
  lib/screens/home.dart
  lib/screens/profile.dart
  lib/screens/submission.dart
Labels: :pencil2: styling
